# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareconfiguration',
            old_name='architecture',
            new_name='arch',
        ),
        migrations.RenameField(
            model_name='softwareconfiguration',
            old_name='operating_system',
            new_name='os',
        ),
        migrations.AddField(
            model_name='softwareconfiguration',
            name='tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
