# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160220_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareconfiguration',
            old_name='value',
            new_name='command',
        ),
        migrations.AddField(
            model_name='softwareconfiguration',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
