# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160221_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareconfiguration',
            name='arch',
            field=models.CharField(choices=[('32bit', '32-bit'), ('64bit', '64-bit'), ('both', 'both')], default='64bit', max_length=10),
        ),
    ]
